#include <iostream>

using namespace std;

int main(){
    //PASO 1: DECLARAR VARIABLES ENTERAS: DIA, MES, AÑO
    //PASO 2: SOLICITAR AL USUARIO: DIA, MES AÑO
    //PASO 3: CON UN SWITHC EVALUAR MES CON 31 DIAS: ENE, MAR, MAY, JUL, AGO, OCT, DIC
        //PASO 3.1: SI DIAS ENTRE 1 Y 31, FECHA VALIDA, DE LO CONTRARIO NO VALIDO
    //PASO 4: AGREGAR CASE PARA MESES CON 30 DIAS: ABR, JUN, SEP, NOV
        //PASO 4.1: SI DIA ENTRE 1 Y 30, FECHA VALIDA, CASO CONTRARIO, INVALIDA
    //PASO 5: CASE FEBRERO
        //PASO 5.1: EVALUAR SI AÑO ES BISIESTO
            //PASO 5.1.1: SI ES BISIESTO Y DIA ENTRE 1 Y 29, FECHA VALIDA, CASO CONTRARIO, INVALIDA
        //PASO 5.2: AÑO NO BISIESTO
            //PASO 5.1.2: SI DIA ENTRE 1 Y 28, FECHA VALIDA, CASO CONTRARIO, INVALIDA
    return 0;
}